name = "howoldisminecrafttoday"
main = "src/worker.js"
compatibility_date = "2024-03-26"

[placement]
mode = "smart"

[site]
bucket = "./assets"

[[kv_namespaces]]
id = "07da5c187a9e4d18aa417816a2dedaf3"
binding = "MC_VERSION_CACHE"
